# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
