# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamath', '0002_auto_20160215_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
