# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=30)),
                ('last_name', models.CharField(default='last name', max_length=30)),
                ('email', models.EmailField(default='email@website.com', max_length=50)),
                ('password', models.CharField(max_length=144)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
